# LOGGING OPTIONS #
# Should we log to console? true/false
logConsole: true
logFile: true
# Enter discord webhook url, to have it disabled set to "disabled"
all_logs_webhook: "disabled"
staff_logs_webhook: "disabled"

# Griefing prevention #

# Should we block tnt explosions? true/false
blockTnt: false

#Should we block endcrystals, Doesn't apply to the end dimension
blockCrystal: false

